version: '3'
services:

  db:
    image: postgres:11
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: tictac
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tictactoedev_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    command: bash -c "make tests && make migrate && make start"
    # command: bash -c "make migrate && make start"
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  pgdata: