version: '3'
services:

  db:
    image: postgres:11
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: tictac
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tictactoedev_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data/redis_data/

  web:
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    command: bash -c "sh ./scripts/prestart.sh && make start"
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  redis_data:
  pgdata: