version: '3'
services:
  web:
    build: .
    restart: always
    volumes:
    - .:/app
    command: bash -c "sh ./scripts/prestart.sh && gunicorn server.main:init_app --config python:config.gunicorn"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tictac
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tictactoedev_db
    ports:
      - "8004:5432"

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/conf.d/web.conf:/etc/nginx/conf.d/web.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

volumes:
  pgdata:

networks:
  default:
    external:
      name: webproxy