version: '3'
services:
  nginx:
    depends_on:
      - web
    image: nginx:stable
    volumes:
      - ./nginx/conf.d/web.conf:/etc/nginx/conf.d/web.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    restart: always
    ports:
      - 80:8888
  web:
    depends_on:
      - postgres
      - redis
    build: .
    restart: always
    command: bash -I -c "gunicorn server.main:server.main --config python:config.gunicorn"
    links:
      - postgres
      - redis
    volumes:
      - .:/app
    expose:
      - "8080"
    ports:
      - 8080:8080
  postgres:
    build:
      context: ./docker
      dockerfile: db.Dockerfile
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "8004:5432"
  redis:
    image: redis:latest
    volumes:
      - ./data/redis_data:/data
    ports:
      - "6380:6379"

networks:
  default:
    external:
      name: webproxy