"""first migration

Revision ID: 2e023f3252a8
Revises: 
Create Date: 2021-01-07 04:04:22.227065

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2e023f3252a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameinstance',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('next_turn', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('players',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gameplayerstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move_type', sa.String(length=10), nullable=False),
    sa.Column('game_name', sa.String(length=64), nullable=True),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['game_name'], ['gameinstance.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_name'], ['players.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('square', sa.Integer(), nullable=True),
    sa.Column('move_type', sa.String(length=10), nullable=True),
    sa.Column('game_name', sa.String(length=64), nullable=True),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['game_name'], ['gameinstance.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_name'], ['players.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('gameplayerstats')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('gameinstance')
    # ### end Alembic commands ###
