"""first migration

Revision ID: b8a44b582e9e
Revises: 2e023f3252a8
Create Date: 2021-01-07 04:06:13.598100

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b8a44b582e9e'
down_revision = '2e023f3252a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gameinstance', ['name'])
    op.create_unique_constraint(None, 'gameplayerstats', ['id'])
    op.create_unique_constraint(None, 'moves', ['id'])
    op.create_unique_constraint(None, 'players', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'moves', type_='unique')
    op.drop_constraint(None, 'gameplayerstats', type_='unique')
    op.drop_constraint(None, 'gameinstance', type_='unique')
    # ### end Alembic commands ###
