"""first migration

Revision ID: e7093b1fa15c
Revises: b8a44b582e9e
Create Date: 2021-01-07 04:21:09.553288

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e7093b1fa15c'
down_revision = 'b8a44b582e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gameinstance_name_key', 'gameinstance', type_='unique')
    op.drop_constraint('gameplayerstats_id_key', 'gameplayerstats', type_='unique')
    op.drop_constraint('moves_id_key', 'moves', type_='unique')
    op.drop_constraint('players_name_key', 'players', type_='unique')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=True)
    op.create_unique_constraint('players_name_key', 'players', ['name'])
    op.create_unique_constraint('moves_id_key', 'moves', ['id'])
    op.create_unique_constraint('gameplayerstats_id_key', 'gameplayerstats', ['id'])
    op.create_unique_constraint('gameinstance_name_key', 'gameinstance', ['name'])
    # ### end Alembic commands ###
